// Week 5/handson_08_vue/student_portal_vue/src/components/CourseCard.vue
<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String
});

defineEmits(['enroll']);
</script>

<template>
  <article class="course-card">
    <h3>{{ name }}</h3>
    <p>Code: {{ code }}</p>
    <span>Credits: {{ credits }}</span>
    <button @click="$emit('enroll')">Enroll</button>
  </article>
</template>

// Week 5/handson_05_06_react/student_portal_react/src/components/CourseCard.jsx
import { useDispatch } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { enroll } from '../stores/enrollmentSlice';

function CourseCard({ id, name, code, credits, grade }) {
  const dispatch = useDispatch();
  const navigate = useNavigate();

  const handleEnroll = () => {
    dispatch(enroll({ id, name, code, credits, grade }));
    navigate('/profile');
  };

  return (
    <article className="course-card">
      <h3>{name}</h3>
      <p>Code: {code}</p>
      <span>Credits: {credits}</span>
      <button onClick={handleEnroll}>Enroll</button>
    </article>
  );
}

export default CourseCard;
